version: '3.9'
services:
  postgres:
    image: postgres:17
    container_name: crm_ideia_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=crmuser
      - POSTGRES_PASSWORD=crmpassword
      - POSTGRES_DB=crmdb
    ports:
      - "5432:5432"
    volumes:
      - crm_ideia_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: crm_ideia_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  crm_ideia_pg_data:
